import numpy as np
import json
import os
import matplotlib.pyplot as plot
import re
import scarabee as scrb
from viz_neutronics.plottingFunctions import readOutputs, findKeffMC, plotSpatialTallyMC, rmsError, visualiseQuarter, normalise_plots, label_plot, apply_indices, octantFromQuart
from viz_neutronics.transport_correction import write_mgXS_file
import logging

logger = logging.getLogger(__name__)


# Global plot settings
# Better subplot spacing
plot.rcParams['figure.constrained_layout.use'] = True
plot.rcParams['axes.grid'] = False                       # Gridline
# Line width. Default is 1.5
plot.rcParams['lines.linewidth'] = 1.5


def transXS_inscatter(hom_XS: scrb.CrossSection, num_groups: int):
    """Takes Scarabée homogenised cross section and number of groups as input, 
    extracts the inscatter transport cross section for all groups and makes a ndarray.

    Args:
        hom_XS (scrb.CrossSection): Homogenised cross sections set
        num_groups (int): Number of energy groups
    """

    Etr_inscatter = []
    for energy_group in range(num_groups):
        Etr_inscatter.append(hom_XS.Etr(energy_group))
    Etr_inscatter = np.array(Etr_inscatter)
    return Etr_inscatter


def transXS_flux_limited(hom_XS: scrb.CrossSection, hom_flux: np.ndarray[np.float64]):
    """Takes Scarabée homogenised cross section and flux as input, returns a flux-limited transport cross section.

    Args:
        hom_XS (scrb.CrossSection): Homogenised cross sections set
        hom_flux (np.ndarray[np.float64]): Homogenised flux array
    """

    ngroups = hom_flux.shape[0]
    s1_array = np.zeros((ngroups, ngroups))
    product = np.zeros(ngroups)
    delta_tr_array = np.zeros(ngroups)
    Et_array = np.zeros(ngroups)

    for energy_out in range(ngroups):
        product[energy_out] = 0
        Et_array[energy_out] = hom_XS.Et(energy_out)
        for energy_in in range(ngroups):
            s1_array[energy_in, energy_out] = hom_XS.Es(
                1, energy_in, energy_out)
            product[energy_out] += s1_array[energy_in,
                                            energy_out] * hom_flux[energy_in]
        delta_tr_array[energy_out] = np.sum(
            product[energy_out]) / hom_flux[energy_out]

    Etr_fl_array = Et_array - delta_tr_array
    return Etr_fl_array


def transXS_outscatter(hom_XS: scrb.CrossSection, hom_flux: np.ndarray[np.float64]):
    """Takes Scarabée homogenised cross section and flux as input, returns an outscatter transport cross section.

    Args:
        hom_XS (scrb.CrossSection): Homogenised cross sections set
        hom_flux (np.ndarray[np.float64]): Homogenised flux array
    """

    ngroups = hom_flux.shape[0]
    s1_array = np.zeros((ngroups, ngroups))
    Et_array = np.zeros(ngroups)

    for energy_out in range(ngroups):
        Et_array[energy_out] = hom_XS.Et(energy_out)
        for energy_in in range(ngroups):
            s1_array[energy_in, energy_out] = hom_XS.Es(
                1, energy_in, energy_out)

    s1g_array = np.sum(s1_array, 1)

    delta_tr_array = s1g_array

    Etr_os_array = Et_array - delta_tr_array

    return Etr_os_array


def display_material_isotopes(material: scrb.Material):
    print('\n' + material.name)
    for nuclide in material.composition.nuclides:
        print(nuclide.name, material.atom_density(nuclide.name))


def findKeff_fromFuelAssembly(scarab_text_log: str):
    """This works specifically for PWR assembly output log files. 
    Taking the second instance of keff seems to work, but 
    sometimes when running a full core, the individual fuel 
    assembly logs seem to get lost. I think the current set-up 
    in EPR core works well for now.

    Args:
        scarab_text_log (str): .txt file generated by Scarabee for a fuel assembly 

    Returns:
       float: The k-eff (or k-inf) for the fuel assembly
    """
    file = open(scarab_text_log, 'r')   # Read scarabee keff from text log
    keff_list = []
    counter = 0
    for line in file:
        if re.search('Kinf', line):
            keff_list.append(float(line.split()[-1]))
            if counter == 1:  # take the second instance of kinf
                break
            else:
                counter += 1
    keff_scarab = keff_list[-1]  # take the last iteration value
    file.close()
    return keff_scarab


def storeAssemblyJSON(assembly, name, outputDir, plotting=True, colour_map='magma'):
    """
    Input is a PWRAssembly object that has been solved (using MOC). Extract form factors, keff and max and min pin power.
    Returns the dictionary containing this information, and also plots the power distribution. Creates a human-readable JSON file.
    """
    logger.info('Storing %s assembly MOC data', name)
    outputFilePath = outputDir + '/' + name

    # Extract assembly data
    form_factors = assembly.form_factors.form_factors
    keff = assembly.keff
    max_pin_power = np.max(form_factors)
    logger.info('Calculating minimum non-zero pin powers')
    min_pin_power = np.min(form_factors[form_factors > 1e-6])

    data = {
        'name': name,
        'keff': keff,
        'max_pin_power': max_pin_power,
        'min_pin_power': min_pin_power,
        'form_factors': form_factors.tolist()
    }

    data.update(readDiffusionData(assembly.diffusion_data))

    with open(outputFilePath + "_data.json", "w") as f:
        json.dump(data, f, indent=2)

    if plotting:
        plotAssemFormFactors(outputFilePath + "_data.json",
                             outputDir, colour_map)

    return data


def storeReflectorJSON(refl, newpath='outputs', plotting=True):
    """
    Input is a PWRAssembly object that has been solved (using MOC). Extract form factors, keff and max and min pin power.
    Returns the dictionary containing this information, and also plots the power distribution. Creates a human-readable JSON file.
    """
    logger.info('Storing reflector data')

    outputs_filepath = newpath + '/'
    if not os.path.exists(outputs_filepath):
        os.makedirs(outputs_filepath)

    data = {
        'nodal_flux': refl.nodal_flux.tolist(),
        'few_group_flux': refl.few_group_flux.tolist(),
        'x': refl.x.tolist(),
        'x_interface': refl.x_interface,
        'nem_keff_flux': refl.nem_keff_flux.tolist(),
        'condensation_scheme': refl.condensation_scheme
        }

    data.update(readDiffusionData(refl.diffusion_data))

    with open(outputs_filepath + "reflector_data.json", "w") as f:
        json.dump(data, f, indent=2)

    if plotting:
        plotReflFlux(outputs_filepath + "reflector_data.json",outputs_filepath)

    return data


def readDiffusionData(diff_data: scrb.DiffusionData):
    """Returns a dictionary containing diffusion data"""
    ngroups = diff_data.ngroups

    D = np.zeros(ngroups)
    Ea = np.zeros(ngroups)
    Er = np.zeros(ngroups)
    Ef = np.zeros(ngroups)
    vEf = np.zeros(ngroups)
    nu = np.zeros(ngroups)
    chi = np.zeros((ngroups))
    Es = np.zeros([ngroups, ngroups])

    for g_out in range(ngroups):
        D[g_out] = diff_data.D(g_out)
        Ea[g_out] = diff_data.Ea(g_out)
        Er[g_out] = diff_data.Er(g_out)
        Ef[g_out] = diff_data.Ef(g_out)
        vEf[g_out] = diff_data.vEf(g_out)
        nu[g_out] = diff_data.nu(g_out)
        chi[g_out] = diff_data.chi(g_out)
        for g_in in range(ngroups):
            Es[g_in][g_out] = diff_data.Es(g_in, g_out)

    data = {
        'adf': diff_data.adf.tolist(),
        'cdf': diff_data.cdf.tolist(),
        'D': D.tolist(),
        'Ea': Ea.tolist(),
        'Er': Er.tolist(),
        'Ef': Ef.tolist(),
        'vEf': vEf.tolist(),
        'nu': nu.tolist(),
        'chi': chi.tolist(),
        'Es': Es.tolist()
    }

    return data


def plotAssemFormFactors(filepath, outputDir, colour_map='magma', tol=1e-6, normalise_by_mean='all', annotate=False, fontsize: float = 2,
        colour: str = 'black',
        dp: float = 3,):
    data = readJSON(filepath)

    name = data['name']
    keff = data['keff']
    adf = np.array(data['adf'])[:, 0]
    D = np.array(data['D'])
    Es = np.array(data['Es'])

    form_factors = np.array(data['form_factors'])
    form_factors = normalise_plots(form_factors, normalise_by_mean)
    
    outputFilePath = outputDir + '/' + name

    print('Plotting {} form factors'.format(data['name']))

    fig, ax = plot.subplots()
    masked = np.ma.masked_where(form_factors < tol, form_factors)
    max_pin_power = np.max(masked) # Must calculate this AFTER normalisation
    min_pin_power = np.min(masked)
    val = ax.imshow(masked, cmap=colour_map)

    ax = label_plot(annotate, masked, ax, fontsize=fontsize, color=colour, dp=dp)

    fig.colorbar(val, ax=ax).minorticks_on()
    fig.suptitle(name + ': Scarabee MOC ' + 'form factors' +
                 '\n$k_{{MOC}}={:.7f}$, pin powers max: {:.2f}, min: {:.2f}'.format(
                     keff, max_pin_power, min_pin_power)
                 + '\nADF: {}'.format(adf)
                 + '\nD: {}'.format(D)
                 + '\nEs {}'.format(Es))
    plot.savefig(outputFilePath + '.svg')
    plot.close()


def plotReflFlux(filepath, outputDir):
    outputs_filepath = outputDir + '/'
    if not os.path.exists(outputs_filepath):
        os.makedirs(outputs_filepath)
    data = readJSON(filepath)

    # Plot flux for each group
    x = data['x']
    ngroups = len(data['condensation_scheme'])

    for g in range(ngroups):
        fig, ax = plot.subplots()
        ax.plot(x, np.array(data['few_group_flux'])[g, :], label="Sn")
        ax.plot(x, np.array(data['nodal_flux'])[g, :], label="NEM Fixed-Source")
        ax.plot(x, np.array(data['nem_keff_flux'])[g, :, 0, 0], label="NEM keff")
        ax.vlines(data['x_interface'], ymin=np.min(np.array(data['few_group_flux'])[g, :]), ymax=np.max(np.array(data['few_group_flux'])[g, :]), colors='black', linestyles='dashed')
        ax.set_xlabel("x [cm]")
        ax.set_ylabel("Flux [Arb. Units]")
        ax.set_title("Group {:}".format(g))      
        ax.grid()
        ax.legend()

        fig.suptitle('Refl ' + 'form factors'
                    + '\nADF: {}'.format(np.array(data['adf'])[:, 0])
                    + ', D: {}'.format(np.array(data['D']))
                    + '\nEs {}'.format(np.array(data['Es'])))

        plot.tight_layout()
        plot.savefig(outputs_filepath + 'reflector_flux_G{:.0f}.svg'.format(g))
        plot.close()

    


def readJSON(filepath):


    with open(filepath) as f:
        data = json.load(f)
    return data


def plotFissRateCompareAssem_MOCMC(outputFileMC: str, outputFileMOC: str, name='assembly', newpath='outputs', rmse_relative_to=None, cmap_colour='Reds', normalise_by_mean='all', annotate=False, fontsize: float = 2,
        colour: str = 'black',
        dp: float = 3,):
    """_summary_

    Args:
        outputFileMC (_type_): _description_
        binFileMOC (_type_): _description_
        scarab_text_log (_type_): _description_
        name (_type_, optional): _description_. Defaults to 'assembly'.
    """    """"""

    outputs_filepath = newpath + '/'
    if not os.path.exists(outputs_filepath):
        os.makedirs(outputs_filepath)

    resScarab = readJSON(outputFileMOC)  # read Scarabee output

    # keff comparison
    keff_SCONE, keff_scarab, keff_diff = compareKeff_ScarabSCONE(
        outputFileMOC, outputFileMC)

    # Fission rate comparison
    tallyname = 'pinFiss'
    fissrateMC, fissrateMC_std = plotSpatialTallyMC(
        outputFileMC, tallyname, plotting=False, normalise_by_mean=normalise_by_mean)
    fissrateScarab = np.array(resScarab['form_factors'], dtype=float)
    fissrateScarab = normalise_plots(fissrateScarab, normalise_by_mean=normalise_by_mean)
    diff = (fissrateScarab - fissrateMC) / fissrateMC

    # Extract Metadata
    # exclude nan values for max calculation but keep them in the plot for clear visualisation of gadolinia and guide tubes
    max_error = np.max(diff[~np.isnan(diff)])
    min_error = np.min(diff[~np.isnan(diff)])

    rms = rmsError(fissrateMC, fissrateScarab, relative_to=rmse_relative_to)

    # plotting
    fig, ax = plot.subplots()
    val = ax.imshow(abs(diff), cmap=cmap_colour, origin='lower')
    ax = label_plot(annotate, abs(diff), ax, fontsize=fontsize, color=colour, dp=dp)
    fig.colorbar(val, ax=ax).minorticks_on()

    fig.suptitle(name + ': Scarabee MOC vs SCONE MC, '
                 '(Abs) relative difference in fission rate. \nMax error={:.2%}, '
                 'min error={:.2%}, \nRMSE={:.2%} relative to {}. \n$k_{{MC}}={:.5f}$, '
                 '$k_{{MOC}}={:.5f}$, diff={:.0f} pcm'.format(max_error, min_error, rms, rmse_relative_to, keff_SCONE, keff_scarab, keff_diff))
    plot.savefig(outputs_filepath + '/' + 'compare_MOC_MC_' +
                 tallyname + '_' + name + '.svg')
    plot.close()


def compareKeff_ScarabSCONE(outputFileMOC: str, outputFileMC):
    """Returns keff from SCONE output json, Scarabee output json, and calculates the difference in pcm, relative to SCONE

    Args:
        outputFileMC (str): _description_
        scarab_text_log (str): _description_
d
    Returns:
        _type_: _description_
    """
    keff_SCONE, keff_SCONE_std = findKeffMC(outputFileMC)
    keff_scarab = readJSON(outputFileMOC)['keff']
    keff_diff = (keff_scarab - keff_SCONE) * 1e5  # pcm
    return keff_SCONE, keff_scarab, keff_diff


def plotDiffusionData(binFileMOC: str, scarab_text_log: str, param: str, name: str, plotting=True):
    resScarab = scrb.DiffusionData.load(binFileMOC)
    value = getattr(resScarab, param)

    if plotting:

        keff_scarab = findKeff_fromFuelAssembly(scarab_text_log)

        # plotting
        fig, ax = plot.subplots()
        val = ax.imshow(value, cmap='magma', origin='lower')
        fig.colorbar(val, ax=ax).minorticks_on()

        fig.suptitle(name + ': Scarabee MOC ' + param +
                     '\n$k_{{MOC}}={:.5f}$'.format(keff_scarab))

        plot.savefig('outputs/' + name + '_' + param + '.png')
        plot.close()
    return value


def storeCoreBuilder(core_builder, z_pin: np.ndarray, x_assem, y_assem, z_assem, newpath):

    # make an output folder to store outputs
    if not os.path.exists(newpath):
        os.makedirs(newpath)

    assembly_powers = core_builder.compute_assembly_powers()
    pin_power = core_builder.compute_pin_powers(z_pin)
    x_pin_centers = core_builder.x_pin_centers
    y_pin_centers = core_builder.y_pin_centers

    solver = core_builder.solver

    logger.info('Making coreBuilder dictionary')
    dictionary = {  # all values are strings so that they get printed into a readable format
        'x_pin_centers': x_pin_centers.tolist(),
        'y_pin_centers': y_pin_centers.tolist(),
        'core_form_factors': core_builder.core_form_factors(x_pin_centers, y_pin_centers, z_pin).tolist(),
        'keff': solver.keff,
        'keff_tolerance': solver.keff_tolerance,
        'avg_flux': solver.avg_flux().tolist(),
        'avg_power': solver.avg_power().tolist(),
        'flux_pinwise': solver.flux(x_pin_centers, y_pin_centers, z_pin).tolist(),
        'flux_assembly_wise': solver.flux(x_assem, y_assem, z_assem).tolist(),
        'flux_tolerance': solver.flux_tolerance,
        'power_pinwise': pin_power.tolist(),
        'power_assembly_wise': assembly_powers.tolist(),
        'ngroups': solver.ngroups
    }
    logger.info('dumping to json %s', newpath +
                'coreBuilder_output.json')

    with open(newpath + 'coreBuilder_output.json', 'w') as f:
        json.dump(dictionary, f, indent=2)


def readCoreBuilder(filepath):
    res = readOutputs(filepath, print_output=True)

    logger.info("Beginning some useful post-processing of Scarabée results:")

    flux_pinwise_dict = {}
    flux_assembly_wise_dict = {}
    avg_flux_dict = {}

    for i in range(res.ngroups):

        key = 'flux_pinwise' + str(i)
        logger.debug('Adding dictionary entry %s', key)
        value = np.array(res.flux_pinwise)[i, :, :, 0]
        flux_pinwise_dict[key] = value

        key_assem = 'flux_assembly_wise' + str(i)
        logger.debug('Adding dictionary entry %s', key_assem)
        value_assem = np.array(res.flux_assembly_wise)[i, :, :, 0]
        flux_assembly_wise_dict[key_assem] = value_assem

        key_avg = 'avg_flux' + str(i)
        logger.debug('Adding dictionary entry %s', key_avg)
        value_avg = np.array(res.avg_flux)[i, :, :, 0]
        avg_flux_dict[key_avg] = value_avg
    setattr(res, 'flux_pinwise', flux_pinwise_dict)
    setattr(res, 'flux_assembly_wise', flux_assembly_wise_dict)
    setattr(res, 'avg_flux', avg_flux_dict)

    avg_power = np.array(res.avg_power)
    mean_power = np.mean(avg_power)

    logger.debug(
        " Normalising the average power by its mean value, %s", mean_power)

    avg_power /= mean_power  # Normalise
    avg_power = avg_power[:, :, 0]
    setattr(res, 'avg_power', avg_power)

    setattr(res, 'power_pinwise', np.array(res.power_pinwise)[:, :, 0])
    setattr(res, 'power_assembly_wise', np.array(
        res.power_assembly_wise)[:, :])
    setattr(res, 'core_form_factors', np.array(res.core_form_factors)[:, :, 0])

    return res


def plotFromNodalResObject(resScarab, paramName, normalise_by_mean='all', vmax=None, vmin=None, plotting=True, aspect_ratio=1, indices=None, mgID=None, tol=1e-16, newpath='outputs', annotate=False, cmap_colour='magma', fontsize=2, colour='white', dp=3, view_geometry=None):
    """ Separate the plotting of results object from reading it, so that we don't have to read the open and load the same json file every time we plot something."""
    # Check parameter type
    if type(getattr(resScarab, paramName)) == dict:
        dataDict = getattr(resScarab, paramName)
        attrFoundFlag = False
        for key in dataDict.keys():
            if key[-1] == str(int(mgID)):
                logger.info(
                    'Parsing results to find match to mgID %s, %s', mgID, key)
                attrFoundFlag = True
                value = dataDict[key]
        if attrFoundFlag:
            pass
        else:
            raise ValueError(
                'Parameter {} with mgID {} for plotting was not found'.format(paramName, mgID))

    else:
        value = np.array(getattr(resScarab, paramName))
        mgID = ''  # set for plotting label

    keff = resScarab.keff

    value = apply_indices(indices, value)
    

    if len(value) == 0:
        raise ValueError('Length of values array is 0!')

    if view_geometry is not None:
        ny, nx = value.shape
        if view_geometry == 'quarter':
            # want to reduce the amount of data to just a quarter
            value = value[: (ny+1) // 2, nx // 2:]
        if view_geometry == 'octant':
            value = value[: (ny+1) // 2, nx // 2:]  # first reduce to quarter

            value = octantFromQuart(value)

    value = normalise_plots(
        value, normalise_by_mean=normalise_by_mean, tol=tol)

    if plotting:

        fig, ax1 = plot.subplots(constrained_layout=True)

        values_masked = np.ma.masked_where(value < tol, value)

        val_plot = ax1.imshow(values_masked, cmap=cmap_colour, vmax=vmax,
                              vmin=vmin, origin='lower', aspect=aspect_ratio)

        ax1 = label_plot(annotate, value, ax1,
                         fontsize=fontsize, color=colour, dp=dp)

        fig.colorbar(val_plot, ax=ax1).minorticks_on()

        fig.suptitle('Scarabee ' + paramName +
                     ', $k_{{eff}}$={:.5f}'.format(keff) + '\n{}: Normalised by the mean of {} values\nMax: {:.3f}, Min: {:.3f}'.format(
                         paramName + str(mgID), normalise_by_mean, np.max(values_masked), np.min(values_masked)))

        plot.savefig(newpath + '/' + paramName +
                     str(mgID) + '_nodal.svg')
        plot.close()

    return value



    

def plotSpatialParamNodal(outputJSONScarab, paramName, normalise_by_mean='all', vmax=None, vmin=None, plotting=True, aspect_ratio=1, indices=None, mgID=None, tol=1e-16, newpath='outputs', annotate=False, cmap_colour='magma', fontsize=2, colour='white', dp=3, view_geometry=True):
    """Plots quantity in Cartesian space along with the uncertainty

    Args:
        outputFileScarab (str):             Name of output MC file.
        paramName (str):                    Name of tally to be plotted, set by user in the MC input file.
        normalise_by_mean (str, optional):  Normalise the tally value to the mean value. Defaults to 'all'.
                                                If 'all', the mean of all values is used. 
                                                If 'non-zero', then only non-zero values are used to calculate the mean. 
                                                If None, no normalisation is applied.
        response_index (int, optional):     If multiple responses have been tallied for this clerk, use this index to specify which one to plot. Defaults to 0.
        plotting (Bool) :                   If True, plots and saves a figure. Otherwise just returns the values.
        indices :                           If None, then no slicing is applied. Otherwise, it should be a list of tuples containing the indices (as many tuples as there are dimensions. The slicing is applied before visualise_quarter)
    """
    logger.info('plotting %s from scarabee file %s',
                paramName, outputJSONScarab)
    resScarab = readCoreBuilder(outputJSONScarab)

    # make an output folder to store outputs
    if not os.path.exists(newpath):
        os.makedirs(newpath)

    value = plotFromNodalResObject(resScarab, paramName, normalise_by_mean, vmax, vmin, plotting, aspect_ratio, indices,
                                   mgID, tol, newpath, annotate, cmap_colour, fontsize, colour, dp, view_geometry)
    return value


def plot_nodal_results(outputFileScarab, normalise_by_mean='all', vmax=None, vmin=None, aspect_ratio=1, tol=1e-16, newpath='outputs', annotate=False, cmap_colour='magma', fontsize=2, colour='white', dp=3, view_geometry=True):


    resScarab = readCoreBuilder(outputFileScarab)
    indices_pins = [(17, -17), (17, -17)]
    indices_assem = [(1, -1), (1, -1)]

    # make an output folder to store outputs
    if not os.path.exists(newpath):
        os.makedirs(newpath)

    ngroups = resScarab.ngroups

    # Flux
    for g in range(ngroups):
        mgID = g
        # assemblies
        plotFromNodalResObject(resScarab, paramName='flux_assembly_wise', normalise_by_mean=normalise_by_mean, vmax=vmax, vmin=vmin, plotting=True, aspect_ratio=aspect_ratio, indices=indices_assem,
                               mgID=mgID, tol=tol, newpath=newpath, annotate=annotate, cmap_colour=cmap_colour, fontsize=fontsize, colour=colour, dp=dp, view_geometry=view_geometry)
        # pins
        plotFromNodalResObject(resScarab, paramName='flux_pinwise', normalise_by_mean=normalise_by_mean, vmax=vmax, vmin=vmin, plotting=True, aspect_ratio=aspect_ratio, indices=indices_pins,
                               mgID=mgID, tol=tol, newpath=newpath, annotate=False, cmap_colour=cmap_colour, fontsize=fontsize, colour=colour, dp=dp, view_geometry=view_geometry)
        # average flux
        plotFromNodalResObject(resScarab, paramName='avg_flux', normalise_by_mean=normalise_by_mean, vmax=vmax, vmin=vmin, plotting=True, aspect_ratio=aspect_ratio, indices=None,
                               mgID=mgID, tol=tol, newpath=newpath, annotate=False, cmap_colour=cmap_colour, fontsize=fontsize, colour=colour, dp=dp, view_geometry=view_geometry)

    # Fission rates
    plotFromNodalResObject(resScarab, paramName='power_assembly_wise', normalise_by_mean=normalise_by_mean, vmax=vmax, vmin=vmin, plotting=True, aspect_ratio=aspect_ratio, indices=indices_assem,
                           mgID=None, tol=tol, newpath=newpath, annotate=annotate, cmap_colour=cmap_colour, fontsize=fontsize, colour=colour, dp=dp, view_geometry=view_geometry)
    plotFromNodalResObject(resScarab, paramName='power_pinwise', normalise_by_mean=normalise_by_mean, vmax=vmax, vmin=vmin, plotting=True, aspect_ratio=aspect_ratio, indices=indices_pins,
                           mgID=None, tol=tol, newpath=newpath, annotate=False, cmap_colour=cmap_colour, fontsize=fontsize, colour=colour, dp=dp, view_geometry=view_geometry)

    # average power
    plotFromNodalResObject(resScarab, paramName='avg_power', normalise_by_mean=normalise_by_mean, vmax=vmax, vmin=vmin, plotting=True, aspect_ratio=aspect_ratio, indices=None,
                           mgID=None, tol=tol, newpath=newpath, annotate=False, cmap_colour=cmap_colour, fontsize=fontsize, colour=colour, dp=dp, view_geometry=view_geometry)

    # core form factors
    plotFromNodalResObject(resScarab, paramName='core_form_factors', normalise_by_mean=normalise_by_mean, vmax=vmax, vmin=vmin, plotting=True, aspect_ratio=aspect_ratio, indices=indices_pins,
                           mgID=None, tol=tol, newpath=newpath, annotate=False, cmap_colour=cmap_colour, fontsize=fontsize, colour=colour, dp=dp, view_geometry=view_geometry)


def plotSpatialParam_CompareNodalMC(outputFileMC, outputFileNodal, tallyName_MC, paramNameNodal, normalise_by_mean='all',  response_index_MC=0, plotting=True, visualise_quarter_MC=False, aspect_ratio=1, indicesNodal=None, indicesMC=None, mgID=None, annotate=False, newpath='outputs', cmap_colour='jet', tol=1e-16, vmax=None, vmin=None, fontsize=5, colour='white', dp=3, view_geometry=None, average_along_diag=False, rmse_relative_to=None):
    # make an output folder to store outputs
    if not os.path.exists(newpath):
        os.makedirs(newpath)

    value_MC, std_MC = plotSpatialTallyMC(outputFileMC, tallyName=tallyName_MC, normalise_by_mean=normalise_by_mean, response_index=response_index_MC, group_index=mgID,
                                          visualise_quarter=visualise_quarter_MC, average_along_diag=average_along_diag, newpath=newpath, annotate=annotate, cmap_colour=cmap_colour, plotting=False, tol=tol, indices=indicesMC)

    value_nodal = plotSpatialParamNodal(outputFileNodal, paramNameNodal, normalise_by_mean=normalise_by_mean, vmax=vmax, vmin=vmin, plotting=False, aspect_ratio=aspect_ratio,
                                        indices=indicesNodal, mgID=mgID, tol=tol, newpath=newpath, annotate=annotate, cmap_colour=cmap_colour, fontsize=fontsize, colour=colour, dp=dp, view_geometry=view_geometry)

    if mgID == None:
        mgID_label = ''  # set for plotting label
    else:
        mgID_label = '_g' + str(mgID)

    # extract labels:
    dummy_value = np.ones((2, 2))
    dummy_std = np.ones((2, 2))
    dummy_value, dummy_std, quarter_label = visualiseQuarter(
        dummy_value, dummy_std, visualise_quarter=visualise_quarter_MC)  # TEMP this is only for MC!!!!

    keff_MC, keff_nodal, keff_diff = compareKeff_ScarabSCONE(
        outputFileNodal, outputFileMC)

    # Calculate quantities
    rel_diff = (value_nodal - value_MC) / value_MC

    rmse = rmsError(value_MC, value_nodal, relative_to=rmse_relative_to)

    if plotting:

        fig, ax1 = plot.subplots()
        masked = np.ma.masked_where(value_nodal < tol, rel_diff)
        val_plot = ax1.imshow(masked * 100, cmap=cmap_colour,
                              origin='lower', aspect=aspect_ratio, vmax=None, vmin=None)

        fig.colorbar(val_plot, ax=ax1, label='%').minorticks_on()

        ax1 = label_plot(annotate, masked, ax1,
                         fontsize=fontsize, color=colour, dp=dp)
        ax1.set_title(
            'Value \nNormalised by the mean\n of {} values'.format(normalise_by_mean))

        fig.suptitle('(Nodal -MC) / MC: relative difference in {} {}. \nMax error={:.3%}, min error={:.3%}, \nRMSE={:.3%} relative to {}.\n$k_{{MC}}={:.5f}$, $k_{{nodal}}={:.5f}$, diff={:.0f} pcm'.format(
            mgID_label[1:],paramNameNodal, np.max(masked), np.min(masked), rmse, rmse_relative_to, keff_MC, keff_nodal, keff_diff) + '\n' + quarter_label)

        plot.savefig(newpath + '/compare_MCNodal' +
                     paramNameNodal + str(mgID_label) + '.svg')




def read_scarab_XS(xs, max_legendre=1):

    ngroups = xs.ngroups
    max_legendre = xs.max_legendre_order

    # Initialise arrays
    Etr_array = np.zeros((ngroups))
    Dtr_array = np.zeros((ngroups))
    Et_array = np.zeros((ngroups))
    Ea_array = np.zeros((ngroups))
    Ef_array = np.zeros((ngroups))
    vEf_array = np.zeros((ngroups))
    nu_array = np.zeros((ngroups))
    Er_array = np.zeros((ngroups))
    chi_array = np.zeros((ngroups))
    Es_tr_array = np.zeros((ngroups, ngroups))
    Es_array = np.zeros((ngroups, ngroups))

    if max_legendre >= 1:
        Es1_array = np.zeros((ngroups, ngroups))
    elif max_legendre >= 2:
        Es2_array = np.zeros((ngroups, ngroups))
    elif max_legendre >= 3:
        Es3_array = np.zeros((ngroups, ngroups))

    # assign values

    for g in range(ngroups):
        Etr_array[g] = xs.Etr(g)
        Dtr_array[g] = xs.Dtr(g)
        Et_array[g] = xs.Et(g)
        Ea_array[g] = xs.Ea(g)
        Ef_array[g] = xs.Ef(g)
        vEf_array[g] = xs.vEf(g)
        nu_array[g] = xs.nu(g)
        Er_array[g] = xs.Er(g)
        chi_array[g] = xs.chi(g)

        for g_out in range(ngroups):
            Es_tr_array[g, g_out] = xs.Es_tr(g, g_out)
            Es_array[g, g_out] = xs.Es(g, g_out)
            if max_legendre >= 1:
                Es1_array[g, g_out] = xs.Es(1, g, g_out)
            if max_legendre >= 2:
                Es2_array[g, g_out] = xs.Es(2, g, g_out)
            if max_legendre >= 3:
                Es3_array[g, g_out] = xs.Es(3, g, g_out)

    dict_XS = {'ngroups': ngroups,
               'Etr': Etr_array,
               'Dtr': Dtr_array,
               'Et': Et_array,
               'Ea': Ea_array,
               'Ef': Ef_array,
               'vEf': vEf_array,
               'nu': nu_array,
               'Er': Er_array,
               'chi': chi_array,
               'Es_tr': Es_tr_array,
               'Es': Es_array,
               'max_legendre_order': max_legendre
               }
    if max_legendre >= 1:
        dict_XS['Es1'] = Es1_array
    if max_legendre >= 2:
        dict_XS['Es2'] = Es2_array
    if max_legendre >= 3:
        dict_XS['Es3'] = Es3_array
    
    return dict_XS


def scarab_to_SCONE_moderator_XS(asmbly, material_name, newpath):
    moderator_XS = asmbly._moderator_xs

    scarab_XS = read_scarab_XS(moderator_XS)
    capture_XS = scarab_XS['Ef'] + scarab_XS['Ea']

    # transfer to MC SCONE input format

    SCONE_dict = {
        'numberOfGroups': scarab_XS['ngroups'],
        'capture': capture_XS,
        'scatteringMultiplicity': np.ones((scarab_XS['ngroups'], scarab_XS['ngroups'])), # standard PWR libraries count scattering production with fission
        'P0': scarab_XS['Es_tr']
    }

    # if fissile:
    if np.all(scarab_XS['chi']!=0): 
        SCONE_dict['fission'] = scarab_XS['Ef']
        SCONE_dict['nu'] = scarab_XS['nu']
        SCONE_dict['chi'] = scarab_XS['chi']


    print('\nWriting cross sections for', material_name, 'to file.')
    write_mgXS_file(SCONE_dict, material_name, newpath)
    
    return SCONE_dict


