#  Author: Shan Tan-Ya
#  Code to convert multigroup cross sections generated by SCONE into corrected scattering cross sections and scattering multiplicity for use in multigroup calculations by SCONE
# It currently only works for cross sections generated using a materialMap or no spatial map


import os
import json
import scipy.io
import h5py
from mat4py import loadmat, savemat
from pymatreader import read_mat

import matplotlib.pyplot as plot
from viz_neutronics.input2json import dict2obj, parse_mat_to_dict
import numpy as np





def generate_mg_XS(filepath_MC_output : np.array2string, tcType : np.array2string, switch='ON', plotting=False):
    """
    Summary: This script works for Material Maps. If there is no material map...
    
    filepath_MC_output (np.array2string) : The filepath to the Monte Carlo output file containing multigroup cross sections
    tcType (np.array2string) : Transport correction type. Can be either 'flux limited' or 'outscatter'
    switch (np.array2string) : 'ON' or 'OFF' If off, no correction is applied
    """
    print('Applying ' + tcType + ' transport correction to multigroup cross sections')

    # read in MC output file (.mat or .m)
    outputDict = parse_mat_to_dict(filepath_MC_output)

    # read in the relevant parameters from the MC output file

    MC_output = dict2obj(outputDict)
    print('Output dictionary keys are:\n')
    for key in outputDict.keys():
        print('-->', key)

    # sm = MC_output.active.scatteringMatrices

    

    [numGroups] = MC_output.MACRO_NG
    numGroups = int(numGroups)

    [energyBounds_data] = np.flip(np.array(MC_output.MACRO_E))
    EnergyBounds = np.zeros((numGroups,2))
    EnergyBounds[:,0]= energyBounds_data[:-1]
    EnergyBounds[:,1]= energyBounds_data[1:]
    


    # for this run:
    numMat = 1
    MaterialBins = ['material'] 
   
    print('\n{:.0f} energy groups,{:.0f} material (s)'.format(numGroups, numMat))

    [capture_data] = np.array(MC_output.INF_CAPT)
    capture = capture_data[0::2]
    capture_unc = capture_data[1::2] * capture


    [fission_data] = np.array(MC_output.INF_FISS)
    fission = fission_data[0::2]
    fission_unc = fission_data[1::2] * fission

    [total_data] = np.array(MC_output.INF_TOT)
    total = total_data[0::2]
    total_unc = total_data[1::2] * total

    [transportXS_data] = np.array(MC_output.INF_TRANSPXS)
    transportXS = transportXS_data[0::2]
    transportXS_unc = transportXS_data[1::2] * transportXS

    [nu_data] = np.array(MC_output.INF_NUBAR)
    nu = nu_data[0::2]
    nu_unc = nu_data[1::2] * nu

    [chi_data] = np.array(MC_output.INF_CHIT)
    chi = chi_data[0::2]
    chi_unc = chi_data[1::2] * chi

    [D_data] = np.array(MC_output.INF_DIFFCOEF)
    D = D_data[0::2]
    D_unc = D_data[1::2] * D

    # scattering matrices
    [P0_data] = np.array(MC_output.INF_S0)
    P0 = P0_data[0::2]
    P0_unc = P0_data[1::2] * P0
    
    # Scattering multiplicity
    [prod_data_num] = np.array(MC_output.INF_SP0)
    [prod_data_denom] = np.array(MC_output.INF_S0)
    prod_data = prod_data_num/prod_data_denom
    prod = prod_data[0::2]  # numerator
    prod_unc = prod_data[1::2] * prod


    # transportFluxLimited = np.array(sm.transportFluxLimited)[...,0]
    # transportOutScatter = np.array(sm.transportOutScatter)[...,0]



    # reshape scattering XS and scattering multiplicity arrays
    P0 = np.reshape(P0, (numMat, numGroups,numGroups))
    P0_unc = np.reshape(P0_unc, (numMat, numGroups,numGroups))

    prod = np.reshape(prod, (numMat, numGroups,numGroups))
    prod_unc = np.reshape(prod_unc, (numMat, numGroups,numGroups))


    ## CHECKS OR COULD READ IT STRAIGHT FROM THE OUTPUT FILE
    # calculate total XS
    # scatter = np.sum(P0,-1) # sum along each row of the scattering matrix to get the total scatter cross section
    # total = fission + capture + scatter

    
     # scattering matrices
    [scatter_data] = np.array(MC_output.INF_SCATT0)
    scatter = scatter_data[0::2]
    scatter_unc = scatter_data[1::2]



    # calculate transport correction
    # correction_FluxLimited = total - transportFluxLimited
    # correction_OutScatter = total - transportOutScatter

    # uncertainties
   
    # scatter_unc_temp = np.sum(P0_unc,-1) # hope this is right
    # total_unc = fission_unc + capture_unc + scatter_unc_temp



    if switch == 'ON':

        
        P0_corrected = np.copy(P0)
        prod_corrected = np.copy(prod)
        P0_corrected_unc = np.copy(P0_unc)
        # P0_corrected = np.copy(P0)
        # prod_corrected = np.copy(prod)

        # # uncertainty
        # P0_corrected_unc = np.copy(P0_unc)

        # No need to corrections

        for g in range(numGroups):
            correction = total - transportXS
            P0_corrected[..., g,g] = P0[..., g,g] - correction[..., g]

            # uncertainty
            correction_unc = total_unc + transportXS_unc
            P0_corrected_unc[..., g,g] = P0_unc[..., g,g] + correction_unc[..., g]

            
            prod_corrected[..., g,g] = (prod[..., g,g] - 1) * P0[..., g,g] / P0_corrected[..., g,g] + 1        
    
    elif switch == 'OFF':
        print('\nWARNING: No transport correction applied. Argument switch is OFF')
        # no change
        P0_corrected = np.copy(P0)
        prod_corrected = np.copy(prod)

        # uncertainty
        P0_corrected_unc = np.copy(P0_unc)

        

        # if tcType == 'outscatter':
        #     transportXS = transportOutScatter
        #     correction = correction_OutScatter

        #     # uncertainty
        #     transportXS_unc = transportOutScatter_unc
        #     correction_unc = total_unc + transportXS_unc
        # elif tcType == 'flux limited':
        #     transportXS = transportFluxLimited
        #     correction = correction_FluxLimited

        #     # uncertainty
        #     transportXS_unc = transportFluxLimited_unc
        #     correction_unc = total_unc + transportXS_unc

    # Address divide-by-zero issues when P0 cross section is 0. Set scattering multiplicity in these cases to 1 to avoid a NaN.
    print('WARNING: Addressing divide-by-zero issue with P0 by setting scattering mutiplicity to 1 in select cases.')
    prod_corrected=np.where(np.isnan(prod_corrected), 1, prod_corrected)

    # Address issue where a 0 total cross section results in divide-by-zero errors for the transport solver for that group.
    # Locate where total cross section is 0, give a tiny non-zero XS to capture cross section:
    print('WARNING: Addressing divide-by-zero issue with total cross section by setting capture cross section to 1e-3 in this group.')
    capture = np.where(total<1e-15, 0.001, capture)
    
       
    # write an output file for each material name material1, material2 etc.
    newpath = 'materialsInputs'
    if not os.path.exists(newpath):
        os.makedirs(newpath)

    for matIndex in range(numMat):
       
        mat = MaterialBins[matIndex]
        capture_res = np.copy(capture)
        fission_res = np.copy(fission)
        nu_res = np.copy(nu)
        chi_res = np.copy(chi)
        transportXS_res = np.copy(transportXS)
        # correction_res = np.copy(correction)
        total_res = np.copy(total)

        # uncertainty
        total_unc_res = np.copy(total_unc)
        capture_unc_res = np.copy(capture_unc)
        fission_unc_res = np.copy(fission_unc)
        transportXS_unc_res = np.copy(transportXS_unc) 
        # correction_unc_res = np.copy(correction_unc) 



        # elif numMat > 1:
           
        #     [mat] = MaterialBins[matIndex] 
        #     capture_res = np.copy(capture[matIndex])
        #     fission_res = np.copy(fission[matIndex])
        #     nu_res = np.copy(nu[matIndex])
        #     chi_res = np.copy(chi[matIndex])
        #     transportXS_res = np.copy(transportXS[matIndex])
        #     correction_res = np.copy(correction[matIndex])
        #     total_res = np.copy(total[matIndex])


        #     # uncertainty
        #     total_unc_res = np.copy(total_unc[matIndex])
        #     capture_unc_res = np.copy(capture_unc[matIndex])
        #     fission_unc_res = np.copy(fission_unc[matIndex])
        #     transportXS_unc_res = np.copy(transportXS_unc[matIndex]) 
        #     correction_unc_res = np.copy(correction_unc[matIndex]) 


        prod_corrected_res = np.copy(prod_corrected[matIndex])
        P0_corrected_res = np.copy( P0_corrected[matIndex])

        # uncertainty
        P0_corrected_unc_res = np.copy(P0_corrected_unc[matIndex])

        print('\nWriting cross sections for', mat, 'to file.')

        f = open(newpath + '/' + mat, "w")
        
        f.write('\nnumberOfGroups '+ str(numGroups) + ';')
        f.write('\ncapture    (' + np.array2string(capture_res, threshold=np.inf).replace('[','').replace(']','') + ');')
        if np.any(fission_res) == False:
            print('\nNo fission cross section written for {}'.format(mat))
            
        else:
            f.write('\nfission   (' + np.array2string(fission_res, threshold=np.inf).replace('[','').replace(']','') + ');')
            f.write('\nnu ('+ np.array2string(nu_res, threshold=np.inf).replace('[','').replace(']','') + ');')
            f.write('\nchi ('+ np.array2string(chi_res, threshold=np.inf).replace('[','').replace(']','') + ');')
  
        f.write('\nscatteringMultiplicity ('+ np.array2string(prod_corrected_res.flatten(), threshold=np.inf).replace('[','').replace(']','') + ');')
        f.write('\nP0 ('+ np.array2string(P0_corrected_res.flatten(), threshold=np.inf ).replace('[','').replace(']','') + ');')
        f.write('\n' +r'//') # for some reason the file won't run unless these comment signs are at the bottom
    
        if plotting:
            # ENERGY BOUNDS ORDER CORRECTION
            print('\nPlotting cross sections for', mat)
            print('Flipping energy bounds for plotting')
            EnergyBounds_plot = np.flip(np.copy(EnergyBounds))
            print(EnergyBounds_plot.shape)
            

            fig, ax = plot.subplots()

            x = (EnergyBounds_plot[:,0] + EnergyBounds_plot[:,1]) / 2
            widths = (EnergyBounds_plot[:,1]-EnergyBounds_plot[:,0])

            ax.bar(x, fission_res, width=widths,label='fission',color='green', edgecolor='black',)
            ax.bar(x, capture_res, width=widths, label='capture',color='red', edgecolor='black', bottom=fission_res)
            if numGroups == 1:
                print('\nOne energy group only')
                scatter_res = np.sum(P0_corrected_res,1).flatten()
                ax.bar(x, scatter_res, width=widths, label='scatter', color='blue', edgecolor='black', bottom=fission_res+capture_res)
                
                # uncertainty
                scatter_unc_res = np.sum(P0_corrected_unc_res, 1).flatten()

            else:
                scatter_res =  np.sum(P0_corrected_res,1)
                ax.bar(x, scatter_res, width=widths, label='scatter', color='blue', edgecolor='black', bottom=fission_res+capture_res)
                # uncertainty
                scatter_unc_res = np.sum(P0_corrected_unc_res, 1)
            ax.legend()

            sumXS_res = capture_res + fission_res + scatter_res

            # uncertainty
            sumXS_unc = capture_unc_res + fission_unc_res + scatter_unc_res
            ax.errorbar(x, sumXS_res, yerr=sumXS_unc, fmt='none', ecolor='black', elinewidth=0.5, capsize=2, barsabove=True)

            ax.set_xscale('log')

            ax.set_ylabel('cm^-1')
            ax.set_xlabel('MeV')
 
            ax.set_title('{:.0f} macroscopic group cross section(s) for {}.'.format(numGroups, mat))
            plot.grid()
            plot.savefig(newpath + '/'+'Cross-sections_' + mat + '.svg')
            plot.close()


            # plot transport corrections in the same way, sharing some variables.
            # print('\nPlotting transport corrections for', mat)
            
            # fig, ax = plot.subplots()
            # ax.bar(x, correction_res, width=widths,label='Transport correction',color='orange', edgecolor='black')

            # # uncertainty
            # ax.errorbar(x, correction_res, yerr=correction_unc_res, fmt='none', ecolor='black', elinewidth=0.5, capsize=2)
         
            # ax.set_xscale('log')
            # ax.set_ylabel('cm^-1')
            # ax.set_xlabel('MeV')
            # ax.set_title('{:.0f} {} transport correction(s) for {}.'.format(numGroups, tcType, mat))
            # plot.grid()
            # plot.savefig(newpath + '/'+'Transport_correction_' + mat + '.svg')
            # plot.close()

            # # plot transport correction ratio in the same way, sharing some variables.
            # print('\nPlotting transport correction ratio for', mat)

            # fig, ax = plot.subplots()

            # ratio = transportXS_res / total_res
            # ax.bar(x, ratio, width=widths,label='Transport correction ratio',color='yellow', edgecolor='black')

            # # uncertainty
            # total_unc_res_rel = total_unc_res / total_res
            # transportXS_unc_res_rel = transportXS_unc_res / transportXS_res
            # ratio_unc_rel = total_unc_res_rel + transportXS_unc_res_rel
            # ratio_unc_abs = ratio_unc_rel * ratio
            # ax.errorbar(x, ratio, yerr=ratio_unc_abs, fmt='none', ecolor='black', elinewidth=0.5, capsize=2)
         
            # ax.set_xscale('log')
            # ax.set_ylabel('transport / total')
            # ax.set_xlabel('MeV')
            # ax.set_title('{:.0f} group, {}\n{} transport cross-section: total cross-section ratio'.format(numGroups,mat, tcType))
            # plot.grid()
            # plot.savefig(newpath + '/'+'Transport_correction_ratio_' + mat + '.svg')
            # plot.close()
            # Also plot the scattering matrices:
            # ideally should plot all XS, P0 and P1.
            print('\nPlotting scattering matrices for', mat)
            fig, ((axP0, axProd)) = plot.subplots(1,2)

            max_abs_P0 = np.max(np.abs(P0_corrected_res))
            # max_abs_prod = np.max(np.abs(prod_corrected_res))

            P0_scale = axP0.imshow(P0_corrected_res, cmap='RdBu_r', vmin=-max_abs_P0, vmax=max_abs_P0)
            prod_scale = axProd.imshow(prod_corrected_res, cmap='Blues', vmin=1)

            fig.colorbar(P0_scale, ax=axP0).minorticks_on()
            fig.colorbar(prod_scale, ax=axProd).minorticks_on()

            # sanity check
            max_P0 = np.max(P0_corrected_res)
            min_P0 = np.min(P0_corrected_res)

            max_prod = np.max(prod_corrected_res)
            min_prod = np.min(prod_corrected_res)

            axP0.set_title('P0\nMin={:.2f}, max={:.2f}'.format(min_P0, max_P0))
            axProd.set_title('Scattering multiplicity.\nMin={:.4f}, max={:.4f}'.format(min_prod, max_prod))

            axP0.set_aspect('equal')
            axProd.set_aspect('equal')
 
            # fig.colorbar(P0)
            fig.suptitle("Scattering matrices, {} group(s), for {}".format(numGroups, mat))
     
            plot.tight_layout()

            plot.savefig(newpath + '/' + 'scattering_colourmap_'  + mat+'.svg')
            plot.close()
            
if __name__=="__main__":
    # test
    # generate_mg_XS("SimplePin_MC_material_output.json", tcType = 'flux limited', switch='OFF')
    # generate_mg_XS("SimplePin_MC_output_64G.json", tcType = 'flux limited', switch='OFF', plotting=True)
    # generate_mg_XS("SimpleSlab_MC_output_1G.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimpleSlab_MC_output_wims172.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimplePin_MC_output_64G.json", tcType = 'flux limited', switch='OFF', plotting=True)
    # generate_mg_XS("SimplePin_MC_output_70G_problematic.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimpleSlabVacuum_MC_output_6G.json", tcType = 'outscatter', switch='OFF', plotting=True) 
    generate_mg_XS("inputs/serpent_output.mat", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("inputs/SimplePin_MC_output_CASMO7.json", tcType = 'flux limited', switch='ON', plotting=True)