# Code to convert multigroup cross sections generated by SCONE into corrected scattering cross sections and scattering multiplicity for use in multigroup calculations by SCONE
# It currently only works for cross sections generated using a materialMap or no spatial map


import os
import json
from decimal import Decimal as dc
import matplotlib.pyplot as plot
from viz_neutronics.input2json import dict2obj
# from input2json import dict2obj # when running test within this script
import numpy as np



def generate_mg_XS(filepath_MC_output : np.array2string, tcType : np.array2string, switch='ON', plotting=False):
    """
    Summary: This script works for Material Maps. If there is no material map...
    filepath_MC_output (np.array2string) : The filepath to the Monte Carlo output file containing multigroup cross sections
    tcType (np.array2string) : Transport correction type. Can be either 'flux limited' or 'outscatter'
    switch (np.array2string) : 'ON' or 'OFF' If off, no correction is applied
    """
    print('Applying ' + tcType + ' transport correction to multigroup cross sections')
    # read in MC output file (json)
    with open(filepath_MC_output) as f:
        outputDict = json.load(f)

    # read in the relevant parameters from the MC output file

    MC_output = dict2obj(outputDict)

    sm = MC_output.active.scatteringMatrices

    EnergyBounds = np.array(sm.EnergyBounds)

    if hasattr(sm, "MaterialBins") == True:

        MaterialBins = np.array(sm.MaterialBins)     
        
        # useful quantities
        numGroups = len(EnergyBounds[1])
        numMat = len(MaterialBins)
        
    else:
   
        MaterialBins = ['material'] # for a single material
        numGroups = len(EnergyBounds[0])
        numMat = 1
    print('{:.0f} energy groups,{:.0f} material (s)'.format(numGroups, numMat))


    capture = np.array(sm.capture)[...,0]
    fission = np.array(sm.fission)[...,0]
    transportFluxLimited = np.array(sm.transportFluxLimited)[...,0]
    transportOutScatter = np.array(sm.transportOutScatter)[...,0]
    nu = np.array(sm.nu)[...,0]
    chi = np.array(sm.chi)[...,0]
    P0 = np.array(sm.P0)[...,0]
    prod = np.array(sm.prod)[...,0]

    print('Capture XS')
    print(capture)

    if hasattr(sm, 'P1'):
        P1 = np.array(sm.P1)
        P2 = np.array(sm.P2)
        P3 = np.array(sm.P3)
        P4 = np.array(sm.P4)
        P5 = np.array(sm.P5)
        P6 = np.array(sm.P6)
        P7 = np.array(sm.P7)
    else:
        print('No higher order PN results found')

    # reshape scattering XS and scattering multiplicity arrays

    P0 = np.reshape(P0, (numMat, numGroups,numGroups))
    prod = np.reshape(prod, (numMat, numGroups,numGroups))

    # calculate total XS
    scatter = np.sum(P0,-1) # sum along each row of the scattering matrix to get the total scatter cross section
    total = fission + capture + scatter


    if switch == 'ON':

        # calculate transport correction
        correction_FluxLimited = total - transportFluxLimited
        correction_OutScatter = total - transportOutScatter

        # apply transport correction
        P0_corrected = np.copy(P0)
        prod_corrected = np.copy(prod)
        for g in range(numGroups):
            if tcType == 'outscatter':
                P0_corrected[..., g,g] = P0[..., g,g] - correction_OutScatter[..., g]
            elif tcType == 'flux limited':
                P0_corrected[..., g,g] = P0[..., g,g] - correction_FluxLimited[..., g]
            else:
                raise ValueError('No correction to scattering cross section was applied')

            prod_corrected[..., g,g] = (prod[..., g,g] - 1) * P0[..., g,g] / P0_corrected[..., g,g] + 1

        
        print('P0 corrected')
        print(P0_corrected)
    
    elif switch == 'OFF':
        print('WARNING: No transport correction applied. Argument switch is OFF')
        # no change
        P0_corrected = np.copy(P0)
        prod_corrected = np.copy(prod)
        print('P0')
        print(P0_corrected)


    # writes an output file for each material name material1, material2 etc.

    newpath = 'materialsInputs'
    if not os.path.exists(newpath):
        os.makedirs(newpath)

    for matIndex in range(numMat):
        if numMat == 1:
            mat = MaterialBins[matIndex]
            capture_res = np.copy(capture)
            fission_res = np.copy(fission)
            nu_res = np.copy(nu)
            chi_res = np.copy(chi)
            prod_corrected_res = np.copy(prod_corrected)
            P0_corrected_res = np.copy( P0_corrected)

        elif numMat > 1:
           
            [mat] = MaterialBins[matIndex] 
            capture_res = np.copy(capture[matIndex])
            fission_res = np.copy(fission[matIndex])
            nu_res = np.copy(nu[matIndex])
            chi_res = np.copy(chi[matIndex])
            prod_corrected_res = np.copy(prod_corrected[matIndex])
            P0_corrected_res = np.copy( P0_corrected[matIndex])

        print('Writing cross sections for', mat)

        f = open(newpath + '/' + mat, "w")
        
        f.write('\nnumberOfGroups '+ str(numGroups) + ';')
        f.write('\ncapture    (' + np.array2string(capture_res, threshold=np.inf).replace('[','').replace(']','') + ');')
        if np.any(fission_res) == False:
            print('No fission cross section for {}'.format(mat))
            
        else:
            f.write('\nfission   (' + np.array2string(fission_res, threshold=np.inf).replace('[','').replace(']','') + ');')
            f.write('\nnu ('+ np.array2string(nu_res, threshold=np.inf).replace('[','').replace(']','') + ');')
            f.write('\nchi ('+ np.array2string(chi_res, threshold=np.inf).replace('[','').replace(']','') + ');')
        f.write('\nscatteringMultiplicity ('+ np.array2string(prod_corrected_res.flatten(), threshold=np.inf).replace('[','').replace(']','') + ');')
        f.write('\nP0 ('+ np.array2string(P0_corrected_res.flatten(), threshold=np.inf ).replace('[','').replace(']','') + ');')
        f.write('\n' +r'//') # for some reason the file won't run unless these comment signs are at the bottom
    
        if plotting:
            # ENERGY BOUNDS ORDER CORRECTION
            print('Plotting cross sections for', mat)
            print('WARNING: Energy Bounds are flipped for plotting because of SCONE printout error at time of coding')
            EnergyBounds_plot = np.flip(np.copy(EnergyBounds),1)
            

            fig, ax = plot.subplots()

            x = (EnergyBounds_plot[0] + EnergyBounds_plot[1]) / 2
            widths = (EnergyBounds_plot[1]-EnergyBounds_plot[0])

            ax.bar(x, fission_res, width=widths,label='fission',color='green', edgecolor='black',)
            ax.bar(x, capture_res, width=widths, label='capture',color='red', edgecolor='black', bottom=fission_res)
            if len(EnergyBounds[0]) == 1:
                print('One energy group only')
                ax.bar(x, np.sum(P0_corrected_res,0).flatten(), width=widths, label='scatter', color='blue', edgecolor='black', bottom=fission_res+capture_res)
            else:
                ax.bar(x, np.sum(P0_corrected_res[0],0), width=widths, label='scatter', color='blue', edgecolor='black', bottom=fission_res+capture_res)
            ax.legend()

            ax.set_xscale('log')

            ax.set_ylabel('cm')
            ax.set_xlabel('MeV')
            ax.set_title('{:.0f} macroscopic group cross section(s) for {}.'.format(len(EnergyBounds_plot[0]), mat))
            plot.grid()
            plot.savefig(newpath + '/'+'Cross-sections_' + mat)

            
if __name__=="__main__":
    # test
    # generate_mg_XS("SimplePin_MC_material_output.json", tcType = 'flux limited', switch='OFF')
    generate_mg_XS("SimplePin_MC_output_64G.json", tcType = 'flux limited', switch='OFF', plotting=True)
    # generate_mg_XS("SimpleSlab_MC_output_1G.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimpleSlab_MC_output_wims172.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimplePin_MC_output_64G.json", tcType = 'flux limited', switch='ON', plotting=True)