# Code to convert multigroup cross sections generated by SCONE into corrected scattering cross sections and scattering multiplicity for use in multigroup calculations by SCONE
# It currently only works for cross sections generated using a materialMap or no spatial map


import os
import json
import matplotlib.pyplot as plot
from viz_neutronics.input2json import dict2obj
# from input2json import dict2obj # when running test within this script
import numpy as np



def generate_mg_XS(filepath_MC_output : np.array2string, tcType : np.array2string, switch='ON', plotting=False):
    """
    Summary: This script works for Material Maps. If there is no material map...
    
    filepath_MC_output (np.array2string) : The filepath to the Monte Carlo output file containing multigroup cross sections
    tcType (np.array2string) : Transport correction type. Can be either 'flux limited' or 'outscatter'
    switch (np.array2string) : 'ON' or 'OFF' If off, no correction is applied
    """
    print('Applying ' + tcType + ' transport correction to multigroup cross sections')
    # read in MC output file (json)
    with open(filepath_MC_output) as f:
        outputDict = json.load(f)

    # read in the relevant parameters from the MC output file

    MC_output = dict2obj(outputDict)

    sm = MC_output.active.scatteringMatrices

    EnergyBounds = np.array(sm.EnergyBounds)

    if hasattr(sm, "MaterialBins") == True:

        MaterialBins = np.array(sm.MaterialBins)     
        
        # useful quantities
        numGroups = len(EnergyBounds[1])
        numMat = len(MaterialBins)
        
    else:
   
        MaterialBins = ['material'] # for a single material
        numGroups = len(EnergyBounds[0])
        numMat = 1
    print('\n{:.0f} energy groups,{:.0f} material (s)'.format(numGroups, numMat))


    capture = np.array(sm.capture)[...,0]
    fission = np.array(sm.fission)[...,0]
    transportFluxLimited = np.array(sm.transportFluxLimited)[...,0]
    transportOutScatter = np.array(sm.transportOutScatter)[...,0]
    nu = np.array(sm.nu)[...,0]
    chi = np.array(sm.chi)[...,0]
    P0 = np.array(sm.P0)[...,0]
    prod = np.array(sm.prod)[...,0]


    # uncertainties

    capture_unc = np.array(sm.capture)[...,1]
    fission_unc = np.array(sm.fission)[...,1]
    transportFluxLimited_unc = np.array(sm.transportFluxLimited)[...,1]
    transportOutScatter_unc = np.array(sm.transportOutScatter)[...,1]
    nu_unc = np.array(sm.nu)[...,1]
    chi_unc = np.array(sm.chi)[...,1]
    P0_unc = np.array(sm.P0)[...,1]
    prod_unc = np.array(sm.prod)[...,1]



    if hasattr(sm, 'P1'):
        print('\nHigher order PN cross sections detected')
        P1 = np.array(sm.P1)
        P2 = np.array(sm.P2)
        P3 = np.array(sm.P3)
        P4 = np.array(sm.P4)
        P5 = np.array(sm.P5)
        P6 = np.array(sm.P6)
        P7 = np.array(sm.P7)
    else:
        print('\nNo higher order PN results found')

    # reshape scattering XS and scattering multiplicity arrays
    P0 = np.reshape(P0, (numMat, numGroups,numGroups))
    prod = np.reshape(prod, (numMat, numGroups,numGroups))

    # calculate total XS
    scatter = np.sum(P0,-1) # sum along each row of the scattering matrix to get the total scatter cross section
    total = fission + capture + scatter


    # calculate transport correction
    correction_FluxLimited = total - transportFluxLimited
    correction_OutScatter = total - transportOutScatter

    # uncertainties
    P0_unc = np.reshape(P0_unc, (numMat, numGroups,numGroups))
    prod_unc = np.reshape(prod_unc, (numMat, numGroups,numGroups))
    scatter_unc_temp = np.sum(P0_unc,-1) # hope this is right
    total_unc = fission_unc + capture_unc + scatter_unc_temp



    if switch == 'ON':

        # apply transport correction
        P0_corrected = np.copy(P0)
        prod_corrected = np.copy(prod)

        # uncertainty
        P0_corrected_unc = np.copy(P0_unc)



        for g in range(numGroups):
            if tcType == 'outscatter':
                transportXS = transportOutScatter
                correction = correction_OutScatter
                P0_corrected[..., g,g] = P0[..., g,g] - correction_OutScatter[..., g]

                # uncertainty
                transportXS_unc = transportOutScatter_unc
                correction_unc = total_unc + transportXS_unc
                P0_corrected_unc[..., g,g] = P0_unc[..., g,g] + correction_unc[..., g]
            elif tcType == 'flux limited':
                transportXS = transportFluxLimited
                correction = correction_FluxLimited
                P0_corrected[..., g,g] = P0[..., g,g] - correction_FluxLimited[..., g]

                # uncertainty
                transportXS_unc = transportFluxLimited_unc
                correction_unc = total_unc + transportXS_unc
                P0_corrected_unc[..., g,g] = P0_unc[..., g,g] + correction_unc[..., g]
            else:
                raise ValueError('tctype argument must be one of ["outscatter","flux limited"]. No correction to scattering cross section was applied')
            
            prod_corrected[..., g,g] = (prod[..., g,g] - 1) * P0[..., g,g] / P0_corrected[..., g,g] + 1        
    
    elif switch == 'OFF':
        print('\nWARNING: No transport correction applied. Argument switch is OFF')
        # no change
        P0_corrected = np.copy(P0)
        prod_corrected = np.copy(prod)

        # uncertainty
        P0_corrected_unc = np.copy(P0_unc)

        if tcType == 'outscatter':
            transportXS = transportOutScatter
            correction = correction_OutScatter

            # uncertainty
            transportXS_unc = transportOutScatter_unc
            correction_unc = total_unc + transportXS_unc
        elif tcType == 'flux limited':
            transportXS = transportFluxLimited
            correction = correction_FluxLimited

            # uncertainty
            transportXS_unc = transportFluxLimited_unc
            correction_unc = total_unc + transportXS_unc

    # Address divide-by-zero issues when P0 cross section is 0. Set scattering multiplicity in these cases to 1 to avoid a NaN.
    print('WARNING: Addressing divide-by-zero issue with P0 by setting scattering mutiplicity to 1 in select cases.')
    prod_corrected=np.where(np.isnan(prod_corrected), 1, prod_corrected)

    # Address issue where a 0 total cross section results in divide-by-zero errors for the transport solver for that group.
    # Locate where total cross section is 0, give a tiny non-zero XS to capture cross section:
    print('WARNING: Addressing divide-by-zero issue with total cross section by setting capture cross section to 1e-3 in this group.')
    capture = np.where(total<1e-15, 0.001, capture)
    
       
    # write an output file for each material name material1, material2 etc.
    newpath = 'materialsInputs'
    if not os.path.exists(newpath):
        os.makedirs(newpath)

    for matIndex in range(numMat):
        if numMat == 1:
            mat = MaterialBins[matIndex]
            capture_res = np.copy(capture)
            fission_res = np.copy(fission)
            nu_res = np.copy(nu)
            chi_res = np.copy(chi)
            transportXS_res = np.copy(transportXS)
            correction_res = np.copy(correction)
            total_res = np.copy(total)

            # uncertainty
            total_unc_res = np.copy(total_unc)
            capture_unc_res = np.copy(capture_unc)
            fission_unc_res = np.copy(fission_unc)
            transportXS_unc_res = np.copy(transportXS_unc) 
            correction_unc_res = np.copy(correction_unc) 



        elif numMat > 1:
           
            [mat] = MaterialBins[matIndex] 
            capture_res = np.copy(capture[matIndex])
            fission_res = np.copy(fission[matIndex])
            nu_res = np.copy(nu[matIndex])
            chi_res = np.copy(chi[matIndex])
            transportXS_res = np.copy(transportXS[matIndex])
            correction_res = np.copy(correction[matIndex])
            total_res = np.copy(total[matIndex])


            # uncertainty
            total_unc_res = np.copy(total_unc[matIndex])
            capture_unc_res = np.copy(capture_unc[matIndex])
            fission_unc_res = np.copy(fission_unc[matIndex])
            transportXS_unc_res = np.copy(transportXS_unc[matIndex]) 
            correction_unc_res = np.copy(correction_unc[matIndex]) 


        prod_corrected_res = np.copy(prod_corrected[matIndex])
        P0_corrected_res = np.copy( P0_corrected[matIndex])

        # uncertainty
        P0_corrected_unc_res = np.copy(P0_corrected_unc[matIndex])

        print('\nWriting cross sections for', mat, 'to file.')

        f = open(newpath + '/' + mat, "w")
        
        f.write('\nnumberOfGroups '+ str(numGroups) + ';')
        f.write('\ncapture    (' + np.array2string(capture_res, threshold=np.inf).replace('[','').replace(']','') + ');')
        if np.any(fission_res) == False:
            print('\nNo fission cross section written for {}'.format(mat))
            
        else:
            f.write('\nfission   (' + np.array2string(fission_res, threshold=np.inf).replace('[','').replace(']','') + ');')
            f.write('\nnu ('+ np.array2string(nu_res, threshold=np.inf).replace('[','').replace(']','') + ');')
            f.write('\nchi ('+ np.array2string(chi_res, threshold=np.inf).replace('[','').replace(']','') + ');')
  
        f.write('\nscatteringMultiplicity ('+ np.array2string(prod_corrected_res.flatten(), threshold=np.inf).replace('[','').replace(']','') + ');')
        f.write('\nP0 ('+ np.array2string(P0_corrected_res.flatten(), threshold=np.inf ).replace('[','').replace(']','') + ');')
        f.write('\n' +r'//') # for some reason the file won't run unless these comment signs are at the bottom
    
        if plotting:
            # ENERGY BOUNDS ORDER CORRECTION
            print('\nPlotting cross sections for', mat)
            print('\nWARNING: Energy Bounds are flipped for plotting because of SCONE printout error at time of coding')
            EnergyBounds_plot = np.flip(np.copy(EnergyBounds),1)
            

            fig, ax = plot.subplots()

            x = (EnergyBounds_plot[0] + EnergyBounds_plot[1]) / 2
            widths = (EnergyBounds_plot[1]-EnergyBounds_plot[0])

            ax.bar(x, fission_res, width=widths,label='fission',color='green', edgecolor='black',)
            ax.bar(x, capture_res, width=widths, label='capture',color='red', edgecolor='black', bottom=fission_res)
            if numGroups == 1:
                print('\nOne energy group only')
                ax.bar(x, np.sum(P0_corrected_res,1).flatten(), width=widths, label='scatter', color='blue', edgecolor='black', bottom=fission_res+capture_res)
                
                # uncertainty
                scatter_unc_res = np.sum(P0_corrected_unc_res, 1).flatten()

            else:
                ax.bar(x, np.sum(P0_corrected_res,1), width=widths, label='scatter', color='blue', edgecolor='black', bottom=fission_res+capture_res)
                # uncertainty
                scatter_unc_res = np.sum(P0_corrected_unc_res, 1)
            ax.legend()


            # uncertainty
            sumXS_unc = capture_unc_res + fission_unc_res + scatter_unc_res
            ax.errorbar(x, total_res, yerr=sumXS_unc, fmt='none', ecolor='black', elinewidth=0.5, capsize=2)

            ax.set_xscale('log')

            ax.set_ylabel('cm^-1')
            ax.set_xlabel('MeV')
 
            ax.set_title('{:.0f} macroscopic group cross section(s) for {}.'.format(numGroups, mat))
            plot.grid()
            plot.savefig(newpath + '/'+'Cross-sections_' + mat + '.svg')
            plot.close()


            # plot transport corrections in the same way, sharing some variables.
            print('\nPlotting transport corrections for', mat)
            
            fig, ax = plot.subplots()
            ax.bar(x, correction_res, width=widths,label='Transport correction',color='orange', edgecolor='black')

            # uncertainty
            ax.errorbar(x, correction_res, yerr=correction_unc_res, fmt='none', ecolor='black', elinewidth=0.5, capsize=2)
         
            ax.set_xscale('log')
            ax.set_ylabel('cm^-1')
            ax.set_xlabel('MeV')
            ax.set_title('{:.0f} {} transport correction(s) for {}.'.format(numGroups, tcType, mat))
            plot.grid()
            plot.savefig(newpath + '/'+'Transport_correction_' + mat + '.svg')
            plot.close()

            # plot transport correction ratio in the same way, sharing some variables.
            print('\nPlotting transport correction ratio for', mat)

            fig, ax = plot.subplots()

            ratio = transportXS_res / total_res
            ax.bar(x, ratio, width=widths,label='Transport correction ratio',color='yellow', edgecolor='black')

            # uncertainty
            total_unc_res_rel = total_unc_res / total_res
            transportXS_unc_res_rel = transportXS_unc_res / transportXS_res
            ratio_unc_rel = total_unc_res_rel + transportXS_unc_res_rel
            ratio_unc_abs = ratio_unc_rel * ratio
            ax.errorbar(x, ratio, yerr=ratio_unc_abs, fmt='none', ecolor='black', elinewidth=0.5, capsize=2)
         
            ax.set_xscale('log')
            ax.set_ylabel('transport / total')
            ax.set_xlabel('MeV')
            ax.set_title('{:.0f} group, {}\n{} transport cross-section: total cross-section ratio'.format(numGroups,mat, tcType))
            plot.grid()
            plot.savefig(newpath + '/'+'Transport_correction_ratio_' + mat + '.svg')
            plot.close()
            # Also plot the scattering matrices:
            # ideally should plot all XS, P0 and P1.
            print('\nPlotting scattering matrices for', mat)
            fig, ((axP0, axProd)) = plot.subplots(1,2)

            max_abs_P0 = np.max(np.abs(P0_corrected_res))
            # max_abs_prod = np.max(np.abs(prod_corrected_res))

            P0_scale = axP0.imshow(P0_corrected_res, cmap='RdBu_r', vmin=-max_abs_P0, vmax=max_abs_P0)
            prod_scale = axProd.imshow(prod_corrected_res, cmap='Blues', vmin=1)

            fig.colorbar(P0_scale, ax=axP0).minorticks_on()
            fig.colorbar(prod_scale, ax=axProd).minorticks_on()

            # sanity check
            max_P0 = np.max(P0_corrected_res)
            min_P0 = np.min(P0_corrected_res)

            max_prod = np.max(prod_corrected_res)
            min_prod = np.min(prod_corrected_res)

            axP0.set_title('P0\nMin={:.2f}, max={:.2f}'.format(min_P0, max_P0))
            axProd.set_title('Scattering multiplicity.\nMin={:.4f}, max={:.4f}'.format(min_prod, max_prod))

            axP0.set_aspect('equal')
            axProd.set_aspect('equal')
 
            # fig.colorbar(P0)
            fig.suptitle("Scattering matrices, {} group(s), for {}".format(numGroups, mat))
     
            plot.tight_layout()

            plot.savefig(newpath + '/' + 'scattering_colourmap_'  + mat+'.svg')
            plot.close()
            
if __name__=="__main__":
    # test
    # generate_mg_XS("SimplePin_MC_material_output.json", tcType = 'flux limited', switch='OFF')
    # generate_mg_XS("SimplePin_MC_output_64G.json", tcType = 'flux limited', switch='OFF', plotting=True)
    # generate_mg_XS("SimpleSlab_MC_output_1G.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimpleSlab_MC_output_wims172.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimplePin_MC_output_64G.json", tcType = 'flux limited', switch='OFF', plotting=True)
    # generate_mg_XS("SimplePin_MC_output_70G_problematic.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimpleSlabVacuum_MC_output_6G.json", tcType = 'outscatter', switch='OFF', plotting=True) 
    generate_mg_XS("SimplePin_MC_output_10^8.json", tcType = 'flux limited', switch='ON', plotting=True)
    # generate_mg_XS("SimplePin_MC_output_CASMO7.json", tcType = 'flux limited', switch='ON', plotting=True)